# Site settings
title: Blue Fenix Productions
email: support@bluefenix.net
description: Simple Solutions from a Professional Geek.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bluefenix.net" # the base hostname & protocol for your site

phone: (713) 364-6419

twitter_username: bluefenix_net

mastadon_username:
@blue_fenix@hachyderm.io

github_username: chrispelatari

# Build settings
markdown: kramdown
