# Site settings
title: Blue Fenix Productions
email: chris@bluefenix.net
description: Simple digital solutions by a Professional Geek.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bluefenix.net" # the base hostname & protocol for your site

phone: (346) 634-3230

blog: chris.pelatari.com/about

mastodon: hachyderm.io/@blue_fenix

github_username: ChrisPelatari

# Build settings
markdown: kramdown
