# Site settings
title: Blue Fenix Productions
email: support@bluefenix.net
description: Simple digital solutions by a Professional Geek.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bluefenix.net" # the base hostname & protocol for your site

phone: (281) 684-5688

blog: chris.pelatari.com

mastodon: hachyderm.io/@blue_fenix

github_username: chrispelatari

# Build settings
markdown: kramdown
