# Site settings
title: Blue Fenix Productions
email: bluefenixpro@pm.me
description: Simple Solutions. Professional Geek.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bluefenix.net" # the base hostname & protocol for your site

twitter_username: bluefenixpro
github_username: chrispelatari

# Build settings
markdown: kramdown
