/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Abstract1: typeof import('./components/Abstract1.vue')['default']
    Abstract2: typeof import('./components/Abstract2.vue')['default']
    Abstract3: typeof import('./components/Abstract3.vue')['default']
    Abstract4: typeof import('./components/Abstract4.vue')['default']
    Client: typeof import('./components/Client.vue')['default']
    Drawer: typeof import('./components/core/Drawer.vue')['default']
    EducationCard: typeof import('./components/EducationCard.vue')['default']
    Heading: typeof import('./components/core/Heading.vue')['default']
    Hero: typeof import('./views/Hero.vue')['default']
    LetsTalk: typeof import('./views/LetsTalk.vue')['default']
    Project: typeof import('./components/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./components/core/Section.vue')['default']
    Skill: typeof import('./components/Skill.vue')['default']
    SocialContacts: typeof import('./components/SocialContacts.vue')['default']
    Subheading: typeof import('./components/core/Subheading.vue')['default']
    Text: typeof import('./components/core/Text.vue')['default']
    WhatICanDoForYou: typeof import('./views/WhatICanDoForYou.vue')['default']
    WhatIKnow: typeof import('./views/WhatIKnow.vue')['default']
    WhatIveDone: typeof import('./views/WhatIveDone.vue')['default']
    WhatMyClientsSay: typeof import('./views/WhatMyClientsSay.vue')['default']
    WhereIveBeen: typeof import('./views/WhereIveBeen.vue')['default']
    WhoIAm: typeof import('./views/WhoIAm.vue')['default']
  }
}
